services:
  - type: web
    name: interns-api
    plan: free
    region: ohio
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_RUNNING_IN_CONTAINER
        value: true
      - key: ASPNETCORE_URLS
        value: http://+:$PORT
      - key: TZ
        value: UTC
    autoDeploy: true
