services:
  - type: web
    name: interns-api
    runtime: dotnet
    plan: free
    region: ohio
    buildCommand: |
      dotnet restore
      dotnet build --configuration Release
      dotnet publish --configuration Release --output ./publish
    startCommand: dotnet ./publish/InternsApi.dll
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_RUNNING_IN_CONTAINER
        value: true
      - key: ASPNETCORE_URLS
        value: http://+:$PORT
      - key: TZ
        value: UTC
    autoDeploy: true

